version: "1"
pipelines:
  - name: automated-tests:0.1.0
    description: build automated tests
    events:
      - "github:thecraftman/sample-app:pull_request.opened"
    jobs:
      - name: automated-tests-build
        description: automated-tests-deployment
        packages:
          - git
        steps:
          - echo "automated tests" 
          - chmod +x install_dependencies.sh run_tests.sh
          - ./install_dependencies.sh
          - ./run_tests.sh
