version: "1"
pipelines:
  - name: build-depenencies:0.1.0
    description: build dependencies
    events:
      - "github:thecraftman/sample-app:pull_request.opened"
    jobs:
      - name: dependencies-packages-build
        description: build dependencies
        packages:
          - git
        steps:
          - echo "build dependencies"  
