version: "1"
pipelines:
  - name: pr-comments-pr-opened:0.1.0
    description: pr comment pr opened
    events:
      - "github:thecraftman/sample-app:pull_request.opened"
    jobs:
      - name: pr-comments-pr-opened-build
        description: example build step
        packages:
          - git
        steps:
          - echo "pull request opened" 
